### ISSUE TITLE
cut-out feature是否会加入？

### ISSUE THREAD

**Issue by longxinzhang** [lujiazho/SegDrawer#1]
请问后续能否加入类似于meta sam网页demo版的cut-out抠图功能？
目前SegDrawer虽然可以识别图像，但下载后只是识别的彩色区域，并非原图切片。

**Comment by lujiazho** [comment]
It is possible to cut them in the backend and download them all in .zip file. If it's not too complex (I guess so) I will add it.

**Comment by lujiazho** [comment]
This feature is already added. I will close this issue.
